services:
  nextjs:
    build:
      context: .
      dockerfile: fly-next/Dockerfile
    container_name: flynext_app
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: flynext_db
    restart: always
    environment:
      POSTGRES_USER: flynext
      POSTGRES_PASSWORD: flynextpassword
      POSTGRES_DB: flynextdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  afs:
    build:
      context: .
      dockerfile: afs/Dockerfile.afs
    container_name: afs_service
    restart: always
    ports:
      - "4000:4000"
    environment:
      - AFS_KEY=${AFS_KEY}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: flynext_nginx
    restart: always
    depends_on:
      - nextjs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
